//Note action types
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const ADD_NOTE_FAIL = 'ADD_NOTE_FAIL';
export const EDIT_NOTE_SUCCESS = 'EDIT_NOTE_SUCCESS';
export const EDIT_NOTE_FAIL = 'EDIT_NOTE_FAIL';
export const DELETE_NOTE = 'DELETE_NOTE';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_FAIL = 'DELETE_NOTE_FAIL';
export const USER_NOTES_LOADING = "USER_NOTES_LOADING";
export const GET_USER_NOTES_SUCCESS = "GET_USER_NOTES_SUCCESS";
export const GET_USER_NOTES_FAIL = "GET_USER_NOTES_FAIL";
export const CURR_NOTE_LOADING = "CURR_NOTE_LOADING";
export const GET_CURR_NOTE_SUCCESS = "GET_CURR_NOTE_SUCCESS";
export const GET_CURR_NOTE_FAIL = "GET_CURR_NOTE_FAIL";
export const GENERAL_NOTES_LOADING = "GENERAL_NOTES_LOADING";
export const GET_GENERAL_NOTES_SUCCESS = "GET_GENERAL_NOTES_SUCCESS";
export const GET_GENERAL_NOTES_FAIL = "GET_GENERAL_NOTES_FAIL";
export const CLEAR_QUERY = "CLEAR_QUERY";
export const GET_NOTE_LIKES = "GET_NOTE_LIKES";
export const GET_NOTE_DISLIKES = "GET_NOTE_DISLIKES";
export const GET_NOTE_LIKES_FAIL = "GET_NOTE_LIKES_FAIL";
export const GET_NOTE_DISLIKES_FAIL = "GET_NOTE_DISLIKES_FAIL";
export const ADD_NOTE_LIKE = "ADD_NOTE_LIKE";
export const ADD_NOTE_LIKE_FAIL = "ADD_NOTE_LIKE_FAIL";
export const REMOVE_NOTE_LIKE = "REMOVE_NOTE_LIKE";
export const REMOVE_NOTE_LIKE_FAIL = "REMOVE_NOTE_LIKE_FAIL";
export const ADD_NOTE_DISLIKE = "ADD_NOTE_DISLIKE";
export const ADD_NOTE_DISLIKE_FAIL = "ADD_NOTE_DISLIKE_FAIL";
export const REMOVE_NOTE_DISLIKE = "REMOVE_NOTE_DISLIKE";
export const REMOVE_NOTE_DISLIKE_FAIL = "REMOVE_NOTE_DISLIKE_FAIL";
export const SWAP_TO_LIKE = "SWAP_TO_LIKE";
export const SWAP_TO_LIKE_FAIL = "SWAP_TO_LIKE_FAIL";
export const SWAP_TO_DISLIKE = "SWAP_TO_DISLIKE";
export const SWAP_TO_DISLIKE_FAIL = "SWAP_TO_DISLIKE_FAIL";
export const LIKED_NOTES_LOADING = "LIKED_NOTES_LOADING";
export const GET_LIKED_NOTES_SUCCESS = "GET_LIKED_NOTES_SUCCESS";
export const GET_LIKED_NOTES_FAIL = "GET_LIKED_NOTES_FAIL";

//Comment action types
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';
export const ADD_REPLY_SUCCESS = 'ADD_REPLY_SUCCESS';
export const ADD_REPLY_FAIL = 'ADD-REPLY_FAIL';
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const EDIT_COMMENT_FAIL = 'EDIT_COMMENT_FAIL';
export const DELETE_COMMENT = 'DELETE_COMMENT'; 
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';
export const USER_COMMENTS_LOADING = 'USER_COMMENTS_LOADING';
export const GET_USER_COMMENTS_SUCCESS = 'GET_USER_COMMENTS_SUCCESS';
export const GET_USER_COMMENTS_FAIL = 'GET_USER_COMMENTS_FAIL';
export const GENERAL_COMMENTS_LOADING = 'GENERAL_COMMENTS_LOADING';
export const GET_GENERAL_COMMENTS_SUCCESS = 'GET_GENERAL_COMMENTS_SUCCESS';
export const GET_GENERAL_COMMENTS_FAIL = 'GET_GENERAL_COMMENTS_FAIL'; 
export const SET_REPLY_TO = 'SET_REPLY_TO';
export const CLEAR_REPLY_TO = 'CLEAR_REPLY_TO';
export const SET_CURRENT_COMMENT = 'SET_CURRENT_COMMENT';
export const COMMENT_REPLIES_LOADING = 'COMMENT_REPLIES_LOADING';
export const GET_COMMENT_REPLIES_SUCCESS = 'GET_COMMENT_REPLIES_SUCCESS';
export const GET_COMMENT_REPLIES_FAIL = 'GET_COMMENT_REPLIES_FAIL';

//Auth action Types
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const UPDATE_PROFILE_PICTURE = "UPDATE_PROFILE_PICTURE";
export const UPDATE_PROFILE_PICTURE_FAIL = "UPDATE_PROFILE_PICTURE_FAIL";
export const DELETE_USER_NOTES = "DELETE_USER_NOTES";

//Error action types
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';